[package]
name = "recover-rs"
edition = "2018"
version = "0.1.0"
authors = ["Luc Fauvel <luc.fauvel@hotmail.com>"]

[dependencies]
dialoguer = "0.6.2"
indicatif = "0.14.0"
console = "0.11.2"
log = "0.4.8"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"